### Data Pre-processing and Cleaning

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import pandas as pd
csv_file_path = '/content/drive/MyDrive/DataScienceFinalProject/cleaned_crime_data.csv'
CrimeData = pd.read_csv(csv_file_path)
CrimeData.head()
CrimeData.shape

(8105, 13)

In [3]:
CostOfLiving = pd.read_csv('/content/drive/MyDrive/DataScienceFinalProject/cost_of_living_us.csv')
CostOfLiving.head()
CostOfLiving.shape

(31430, 15)

In [4]:
USCities = pd.read_csv('/content/drive/MyDrive/DataScienceFinalProject/uscities.csv')
USCities.head()
USCities.shape

(28338, 17)

In [5]:
CrimeData.head()

,State,City,Population,V_crime,Murder,Rape,Robbery,Aggravated assault,Property crime,Burglary,Larceny-theft,Motor vehicle theft,Arson2
0,ALABAMA3,Hoover,"85,670",114,4.0,15,27,68,"1,922",128,"1,694",100,2
1,ALASKA,Anchorage,"287,731","3,581",32.0,540,621,"2,388","12,261","1,692","9,038","1,531",93
2,ALASKA,Bethel,"6,544",130,1.0,47,3,79,132,20,84,28,12
3,ALASKA,Bristol Bay Borough,852,2,0.0,0,0,2,20,5,8,7,0
4,ALASKA,Cordova,"2,150",0,0.0,0,0,0,7,1,6,0,0

In [6]:
CrimeData['State'] = CrimeData['State'].str.replace(r'\d+', '', regex=True).str.strip()
CrimeData.head()

,State,City,Population,V_crime,Murder,Rape,Robbery,Aggravated assault,Property crime,Burglary,Larceny-theft,Motor vehicle theft,Arson2
0,ALABAMA,Hoover,"85,670",114,4.0,15,27,68,"1,922",128,"1,694",100,2
1,ALASKA,Anchorage,"287,731","3,581",32.0,540,621,"2,388","12,261","1,692","9,038","1,531",93
2,ALASKA,Bethel,"6,544",130,1.0,47,3,79,132,20,84,28,12
3,ALASKA,Bristol Bay Borough,852,2,0.0,0,0,2,20,5,8,7,0
4,ALASKA,Cordova,"2,150",0,0.0,0,0,0,7,1,6,0,0

In [7]:
CrimeData['City'] = CrimeData['City'].str.upper()
CrimeData.head()

,State,City,Population,V_crime,Murder,Rape,Robbery,Aggravated assault,Property crime,Burglary,Larceny-theft,Motor vehicle theft,Arson2
0,ALABAMA,HOOVER,"85,670",114,4.0,15,27,68,"1,922",128,"1,694",100,2
1,ALASKA,ANCHORAGE,"287,731","3,581",32.0,540,621,"2,388","12,261","1,692","9,038","1,531",93
2,ALASKA,BETHEL,"6,544",130,1.0,47,3,79,132,20,84,28,12
3,ALASKA,BRISTOL BAY BOROUGH,852,2,0.0,0,0,2,20,5,8,7,0
4,ALASKA,CORDOVA,"2,150",0,0.0,0,0,0,7,1,6,0,0

In [8]:
CostOfLiving.head()

,case_id,state,isMetro,areaname,county,family_member_count,housing_cost,food_cost,transportation_cost,healthcare_cost,other_necessities_cost,childcare_cost,taxes,total_cost,median_family_income
0,1,AL,True,"Montgomery, AL MSA",Autauga County,1p0c,8505.72876,3454.91712,10829.16876,5737.47984,4333.81344,0.0000,6392.94504,39254.0532,73010.414062
1,1,AL,True,"Montgomery, AL MSA",Autauga County,1p1c,12067.50240,5091.70788,11588.19288,8659.55640,6217.45896,6147.8298,7422.07836,57194.3256,73010.414062
2,1,AL,True,"Montgomery, AL MSA",Autauga County,1p2c,12067.50240,7460.20308,12361.77720,11581.63260,7075.65816,15824.6940,9769.56228,76141.0308,73010.414062
3,1,AL,True,"Montgomery, AL MSA",Autauga County,1p3c,15257.15040,9952.23924,13452.18600,14503.70760,9134.35620,18802.1892,13101.70320,94203.5328,73010.414062
4,1,AL,True,"Montgomery, AL MSA",Autauga County,1p4c,15257.15040,12182.21400,13744.59840,17425.78560,9942.36396,18802.1892,13469.21880,100823.5200,73010.414062

In [9]:
CostOfLiving['county'].unique().size

1877

In [10]:
USCities.head()

,city,city_ascii,state_id,state_name,county_fips,county_name,lat,lng,population,density,source,military,incorporated,timezone,ranking,zips,id
0,New York,New York,NY,New York,36061,New York,40.6943,-73.9249,18713220,10715,polygon,False,True,America/New_York,1,11229 11226 11225 11224 11222 11221 11220 1138...,1840034016
1,Los Angeles,Los Angeles,CA,California,6037,Los Angeles,34.1139,-118.4068,12750807,3276,polygon,False,True,America/Los_Angeles,1,90291 90293 90292 91316 91311 90037 90031 9000...,1840020491
2,Chicago,Chicago,IL,Illinois,17031,Cook,41.8373,-87.6862,8604203,4574,polygon,False,True,America/Chicago,1,60018 60649 60641 60640 60643 60642 60645 6064...,1840000494
3,Miami,Miami,FL,Florida,12086,Miami-Dade,25.7839,-80.2102,6445545,5019,polygon,False,True,America/New_York,1,33129 33125 33126 33127 33128 33149 33144 3314...,1840015149
4,Dallas,Dallas,TX,Texas,48113,Dallas,32.7936,-96.7662,5743938,1526,polygon,False,True,America/Chicago,1,75287 75098 75233 75254 75251 75252 75253 7503...,1840019440

In [11]:
USCities['city'] = USCities['city'].str.upper()
USCities['state_name'] = USCities['state_name'].str.upper()
USCities['county_name'] = USCities['county_name'].str.upper()
USCities.head()

,city,city_ascii,state_id,state_name,county_fips,county_name,lat,lng,population,density,source,military,incorporated,timezone,ranking,zips,id
0,NEW YORK,New York,NY,NEW YORK,36061,NEW YORK,40.6943,-73.9249,18713220,10715,polygon,False,True,America/New_York,1,11229 11226 11225 11224 11222 11221 11220 1138...,1840034016
1,LOS ANGELES,Los Angeles,CA,CALIFORNIA,6037,LOS ANGELES,34.1139,-118.4068,12750807,3276,polygon,False,True,America/Los_Angeles,1,90291 90293 90292 91316 91311 90037 90031 9000...,1840020491
2,CHICAGO,Chicago,IL,ILLINOIS,17031,COOK,41.8373,-87.6862,8604203,4574,polygon,False,True,America/Chicago,1,60018 60649 60641 60640 60643 60642 60645 6064...,1840000494
3,MIAMI,Miami,FL,FLORIDA,12086,MIAMI-DADE,25.7839,-80.2102,6445545,5019,polygon,False,True,America/New_York,1,33129 33125 33126 33127 33128 33149 33144 3314...,1840015149
4,DALLAS,Dallas,TX,TEXAS,48113,DALLAS,32.7936,-96.7662,5743938,1526,polygon,False,True,America/Chicago,1,75287 75098 75233 75254 75251 75252 75253 7503...,1840019440

In [12]:
CrimeUSCities = pd.merge(CrimeData, USCities, left_on=['City', 'State'], right_on=['city', 'state_name'], how='inner')
CrimeUSCities.head()

,State,City,Population,V_crime,Murder,Rape,Robbery,Aggravated assault,Property crime,Burglary,...,lng,population,density,source,military,incorporated,timezone,ranking,zips,id
0,ALABAMA,HOOVER,"85,670",114,4.0,15,27,68,"1,922",128,...,-86.8064,85768,691,polygon,False,True,America/Chicago,3,35216 35244 35242 35080 35226 35236 35260,1840014795
1,ALASKA,ANCHORAGE,"287,731","3,581",32.0,540,621,"2,388","12,261","1,692",...,-149.1091,288000,65,polygon,False,True,America/Anchorage,2,99518 99515 99517 99516 99513 99540 99567 9958...,1840023385
2,ALASKA,BETHEL,"6,544",130,1.0,47,3,79,132,20,...,-161.7917,6586,57,polygon,False,True,America/Anchorage,3,99559 99545,1840023353
3,ALASKA,CORDOVA,"2,150",0,0.0,0,0,0,7,1,...,-145.6092,2169,13,polygon,False,True,America/Anchorage,3,99574,1840023402
4,ALASKA,CRAIG,"1,313",7,0.0,0,0,7,20,5,...,-133.1165,1262,72,polygon,False,True,America/Sitka,3,99921,1840023520

In [13]:
CrimeUSCities.shape

(6305, 30)

In [14]:
CrimeUSCities.columns.unique()

Index(['State', 'City', 'Population', 'V_crime', 'Murder', 'Rape', 'Robbery',
       'Aggravated assault', 'Property crime', 'Burglary', 'Larceny-theft',
       'Motor vehicle theft', 'Arson2', 'city', 'city_ascii', 'state_id',
       'state_name', 'county_fips', 'county_name', 'lat', 'lng', 'population',
       'density', 'source', 'military', 'incorporated', 'timezone', 'ranking',
       'zips', 'id'],
      dtype='object')

In [15]:
common_counties = set(CrimeUSCities['county_name']).intersection(set(CostOfLiving['county']))
print(f"Number of common counties: {len(common_counties)}")
print(f"Common counties: {common_counties}")

Number of common counties: 0
Common counties: set()

In [16]:
CrimeUSCities.to_csv('MergedData(Crime and Cities).csv')

In [17]:
# prompt: sort county name in ascending order

CrimeUSCities.sort_values(by='county_name', ascending=True, inplace=True)
CrimeUSCities['county_name'].unique()

array(['ABBEVILLE', 'ACADIA', 'ACCOMACK', ..., 'YUBA', 'YUMA', 'ZAVALA'],
      dtype=object)

In [18]:
CostOfLiving.sort_values(by='county', ascending=True, inplace=True)
CostOfLiving['county'].unique()

array(['Abbeville County', 'Acadia Parish', 'Accomack County', ...,
       'Zapata County', 'Zavala County', 'Ziebach County'], dtype=object)

In [19]:
# prompt: remove the word county from CostOfLiving['county']

CostOfLiving['county'] = CostOfLiving['county'].str.replace(' County', '')
CostOfLiving['county'] = CostOfLiving['county'].str.replace(' Parish', '')
CostOfLiving['county'] = CostOfLiving['county'].str.upper()
CostOfLiving['county'].unique()

array(['ABBEVILLE', 'ACADIA', 'ACCOMACK', ..., 'ZAPATA', 'ZAVALA',
       'ZIEBACH'], dtype=object)

In [20]:
common_counties = set(CrimeUSCities['county_name']).intersection(set(CostOfLiving['county']))
print(f"Number of common counties: {len(common_counties)}")
print(f"Common counties: {common_counties}")

Number of common counties: 1300
Common counties: {'CEDAR', 'DAUPHIN', 'RAPIDES', 'ONONDAGA', 'HARPER', 'CHIPPEWA', 'NORFOLK', 'FREMONT', 'BERKELEY', 'WYTHE', 'YUMA', 'BAYFIELD', 'OHIO', 'JERSEY', 'FLORENCE', 'MANITOWOC', 'LAVACA', 'TANEY', 'KARNES', 'PLYMOUTH', 'SMITH', 'PEPIN', 'KAUFMAN', 'HARALSON', 'JACKSON', 'KENT', 'KALAMAZOO', 'CULPEPER', 'RANKIN', 'LOUDON', 'REPUBLIC', 'LEE', 'RAY', 'MERRICK', 'ASCENSION', 'MCCLAIN', 'DUVAL', 'WINKLER', 'PAGE', 'PREBLE', 'GEAUGA', 'LORAIN', 'STANISLAUS', 'MANISTEE', 'BEAVERHEAD', 'MEDINA', 'GIBSON', 'WHITLEY', 'SEBASTIAN', 'NEWBERRY', 'DICKEY', 'KANAWHA', 'SHARP', 'LENAWEE', 'MARLBORO', 'AMADOR', 'STORY', 'RED WILLOW', 'YOLO', 'CHARLOTTE', 'HAWKINS', 'GREENUP', 'LAUREL', 'ISLE OF WIGHT', 'NEVADA', 'BALLARD', 'COWLEY', 'CRITTENDEN', 'MONROE', 'JOHNSTON', 'LAPEER', 'EFFINGHAM', 'SEVIER', 'CRAIG', 'ROWAN', 'LYCOMING', 'SOCORRO', 'NOWATA', 'CROSBY', 'ROUTT', 'INDIAN RIVER', 'SAUNDERS', 'DICKENSON', 'LANE', 'SHERIDAN', 'ST. LAWRENCE', 'PROWERS', 'COMAL', 'PUTNAM', 'MUSCATINE', 'CIBOLA', 'COLLIN', 'DENVER', 'CONCORDIA', 'GREER', 'ESCAMBIA', 'DEAF SMITH', 'PRINCE EDWARD', 'WISE', 'THURSTON', 'MAHASKA', 'TELLER', 'SAN JOAQUIN', 'ROSEAU', 'NELSON', 'BIG HORN', 'IOWA', 'GUNNISON', 'MINNEHAHA', 'EAST BATON ROUGE', 'VANCE', 'CHATHAM', 'SUMNER', 'KAY', 'SPOKANE', 'BLOUNT', 'MERCED', 'ERIE', 'CUYAHOGA', 'BARRON', 'DILLON', 'WILKES', 'MONMOUTH', 'ECTOR', 'LITCHFIELD', 'WALWORTH', 'HUBBARD', 'KINGFISHER', 'MARATHON', 'BLACK HAWK', 'SPARTANBURG', 'CALLOWAY', 'POTTER', 'CAROLINE', 'ST. HELENA', 'ROANOKE', 'STUTSMAN', 'STODDARD', 'STRAFFORD', 'WRIGHT', 'ALGER', 'INDIANA', 'OKALOOSA', 'GREENBRIER', 'MILLS', 'SAN PATRICIO', 'PARMER', 'WINN', 'RUNNELS', 'DENTON', 'MARIN', 'TWIN FALLS', 'ESTILL', 'TATTNALL', 'CHAFFEE', 'TOOELE', 'LAURENS', 'CLINCH', 'COFFEY', 'MARSHALL', 'TULARE', 'ARCHULETA', 'WASATCH', 'MOFFAT', 'ROBERTS', 'BRISTOL', 'DUPLIN', 'COCONINO', 'STARK', 'ADA', 'PALM BEACH', 'VANDERBURGH', 'STEELE', 'BACON', 'FAULKNER', 'MCKENZIE', 'SUSSEX', 'MUHLENBERG', 'BUNCOMBE', 'ROSEBUD', 'VOLUSIA', 'SHENANDOAH', 'MONTEZUMA', 'POLK', 'HUMPHREYS', 'DEWITT', 'COLE', 'SANDOVAL', 'ROOSEVELT', 'FAIRFAX', 'RANDALL', 'MEADE', 'MCDONOUGH', 'BOYLE', 'BRAZORIA', 'LUNENBURG', 'BANKS', 'LAWRENCE', 'DIXON', 'BUCHANAN', 'PEORIA', 'BAY', 'EDMONSON', 'HENDRICKS', 'FREEBORN', 'GLACIER', 'FLEMING', 'DORCHESTER', 'MILAM', 'CABELL', 'MILLE LACS', 'KANE', 'CRAIGHEAD', 'TAOS', 'YELLOW MEDICINE', 'PINAL', 'TURNER', 'RABUN', 'RICHLAND', 'MARINETTE', 'SAC', 'MCLEAN', 'PHILLIPS', 'OUTAGAMIE', 'BECKHAM', 'SANTA BARBARA', 'MERIWETHER', 'BURNETT', 'DODGE', 'CHESHIRE', 'MAVERICK', 'ORLEANS', 'SOLANO', 'EMMET', 'SALT LAKE', 'STAFFORD', 'NORTHAMPTON', 'SIMPSON', 'RAWLINS', 'OTOE', 'SAN FRANCISCO', 'WEXFORD', 'KANKAKEE', 'BLAINE', 'TARRANT', 'SPENCER', 'ATASCOSA', 'ELKO', 'MIAMI', 'SAGUACHE', 'CARVER', 'RUTLAND', 'KALKASKA', 'JASPER', 'WOOD', 'HAYWOOD', 'LARAMIE', 'MONTGOMERY', 'SANILAC', 'MARION', 'YOAKUM', 'BERKSHIRE', 'JO DAVIESS', 'BURLESON', 'PERRY', 'VENTURA', 'CLAYTON', 'MAJOR', 'HOUGHTON', 'IROQUOIS', 'WARREN', 'LEMHI', 'WABAUNSEE', 'CATAWBA', 'MANATEE', 'NOBLES', 'EDDY', 'CARLISLE', 'NEW LONDON', 'OKLAHOMA', 'TIPTON', 'WALLER', 'MECOSTA', 'PEMISCOT', 'FOSTER', 'YAKIMA', 'WETZEL', 'JESSAMINE', 'WATAUGA', 'CECIL', 'GOODING', 'SEQUOYAH', 'CLARE', 'OVERTON', 'PIATT', 'PACIFIC', 'COBB', 'DISTRICT OF COLUMBIA', 'WALLA WALLA', 'CASS', 'TIOGA', 'BONNEVILLE', 'TUSCARAWAS', 'OAKLAND', 'BERGEN', 'ROCKWALL', 'BASTROP', 'INYO', 'CLAIBORNE', 'ANDERSON', 'NICOLLET', 'ACCOMACK', 'FORREST', 'SALEM', 'LYNN', 'SACRAMENTO', 'BUREAU', 'NATCHITOCHES', 'WAUSHARA', 'GRAND', 'UVALDE', 'OBION', 'SHASTA', 'SCHENECTADY', 'DELAWARE', 'OUACHITA', 'ELLSWORTH', 'GLADWIN', 'DAVISON', 'DAVIESS', 'NEMAHA', 'COWETA', 'BERTIE', 'NASSAU', 'PICKAWAY', 'DEKALB', 'GARVIN', 'NODAWAY', 'LIVINGSTON', 'PIMA', 'CALEDONIA', 'FALLON', 'SCHUYLER', 'HARVEY', 'CHAMPAIGN', 'MORRISON', 'BUTTE', 'CAPE GIRARDEAU', 'HEMPSTEAD', 'RAVALLI', 'PAULDING', 'PORTAGE', 'FOREST', 'CLEVELAND', 'RENVILLE', 'SHOSHONE', 'SEQUATCHIE', 'KEWAUNEE', 'SHELBY', 'SCREVEN', 'ARAPAHOE', 'COOS', 'EATON', 'MASSAC', 'HART', 'HARNEY', 'BAXTER', 'CAMDEN', 'EVANS', 'FLATHEAD', 'LAFOURCHE', 'WILLIAMSBURG', 'ASHLAND', 'MAURY', 'MIDDLESEX', 'COOK', 'MOREHOUSE', 'ALAMEDA', 'TODD', 'CONTRA COSTA', 'NEW HANOVER', 'MINGO', 'BURKE', 'SAN LUIS OBISPO', 'GOSHEN', 'GAINES', 'GUADALUPE', 'SUMMIT', 'CADDO', 'TAMA', 'ULSTER', 'PASSAIC', 'GRAYS HARBOR', 'DAVIDSON', 'BRACKEN', 'BACA', 'CLINTON', 'BIG STONE', 'TILLAMOOK', 'SAWYER', 'ALLAMAKEE', 'WAKE', 'MILWAUKEE', 'ATOKA', 'DESCHUTES', 'MORGAN', 'IMPERIAL', 'CARIBOU', 'GRAND FORKS', 'HUNTERDON', 'HANOVER', 'ANGELINA', 'HARFORD', 'DUPAGE', 'MONTAGUE', 'PAWNEE', 'OCEAN', 'FENTRESS', 'BRADLEY', 'WALTON', 'CAMERON', 'DANE', 'BECKER', 'WYANDOT', 'BRUNSWICK', 'TORRANCE', 'PASQUOTANK', 'COCKE', 'HIGHLANDS', 'SANTA ROSA', 'BARNES', 'DARE', 'AUDRAIN', 'CHARLES', 'ASHLEY', 'LAMB', 'FRANKLIN', 'MINIDOKA', 'WOODS', 'OZAUKEE', 'COLUMBIA', 'NACOGDOCHES', 'HIDALGO', 'LIBERTY', 'OKFUSKEE', 'CHAMBERS', 'MENDOCINO', 'MCHENRY', 'PRICE', 'PERQUIMANS', 'BRECKINRIDGE', 'HAYS', 'KENNEBEC', 'IDAHO', 'PITKIN', 'LOVE', 'ST. JOSEPH', 'COAL', 'LEXINGTON', 'CHEMUNG', 'WHARTON', 'GARLAND', 'TANGIPAHOA', 'TUSCOLA', 'JENKINS', 'WAYNE', 'KNOX', 'BLADEN', 'WASECA', 'ANDROSCOGGIN', 'WINDHAM', 'BRAZOS', 'WILLIAMS', 'AVERY', 'GRUNDY', 'RUSSELL', 'TERREBONNE', 'SWISHER', 'GRAVES', 'BANNOCK', 'WHATCOM', 'PICKENS', 'GILPIN', 'GREENWOOD', 'CHICOT', 'BUENA VISTA', 'NASH', 'GRIMES', 'DUBOIS', 'CHOCTAW', 'STE. GENEVIEVE', 'ALAMANCE', 'KANDIYOHI', 'DEFIANCE', 'GEORGETOWN', 'CAMBRIA', 'ROBERTSON', 'STEPHENS', 'ROCK', 'PAYNE', 'KIOWA', 'LAS ANIMAS', 'GREEN LAKE', 'NORTON', 'UINTAH', 'GRATIOT', 'MCCURTAIN', 'HANCOCK', 'MUSKINGUM', 'COCHISE', 'WASHAKIE', 'SANDUSKY', 'ZAVALA', 'ST. FRANCIS', 'YORK', 'FILLMORE', 'KERN', 'ADAMS', 'COLUMBIANA', 'LAUDERDALE', 'SAGINAW', 'DECATUR', 'DURHAM', 'ROCK ISLAND', 'LANCASTER', 'JEFFERSON DAVIS', 'ST. FRANCOIS', 'MERRIMACK', 'AUSTIN', 'GREGG', 'ONTARIO', 'STANLY', 'HAMPSHIRE', 'MAYES', 'SEMINOLE', 'ONEIDA', 'LUCAS', 'PALO ALTO', 'GLENN', 'BROWN', 'OKMULGEE', 'VAN WERT', 'CANNON', 'HARMON', 'SANTA FE', 'MITCHELL', 'TEHAMA', 'ELMORE', 'MISSOULA', 'LICKING', 'DREW', 'PARK', 'ST. CHARLES', 'LEON', 'RACINE', 'EAU CLAIRE', 'HILLSBOROUGH', 'CALUMET', 'BURNET', 'WASCO', 'WAUKESHA', 'CARROLL', 'OTSEGO', 'JEFFERSON', 'OCONEE', 'ST. MARTIN', 'RIO BLANCO', 'BATES', 'MONTCALM', 'LACLEDE', 'NATRONA', 'COVINGTON', 'GRANVILLE', 'CARTERET', 'LEBANON', 'ISANTI', 'NUECES', 'FANNIN', 'LIMESTONE', 'TAYLOR', 'CURRY', 'SAN SABA', 'WICOMICO', 'BOWIE', 'SARPY', 'HALE', 'GILES', 'KLAMATH', 'MONONGALIA', 'WHITESIDE', 'AUDUBON', 'SMYTH', 'BROOME', 'BERRIEN', 'SEDGWICK', 'UPSHUR', 'HOCKLEY', 'HALIFAX', 'SAN JUAN', 'WILLIAMSON', 'VERMILLION', 'ROBESON', 'GUILFORD', 'YANKTON', 'RICHMOND', 'GREEN', 'BERKS', 'UTAH', 'BEXAR', 'TILLMAN', 'ROANE', 'KENOSHA', 'MESA', 'ST. TAMMANY', 'BARREN', 'WASHINGTON', 'MAHONING', 'CHEATHAM', 'WABASHA', 'LEA', 'THOMAS', 'CORYELL', 'IONIA', 'NEW CASTLE', 'OTERO', 'GOGEBIC', 'RALLS', 'PENOBSCOT', 'SCOTTS BLUFF', 'SABINE', 'ARENAC', 'POWER', 'WEBER', 'EASTLAND', 'MCCORMICK', 'JOHNSON', 'BOX ELDER', 'ALBANY', 'BULLITT', 'SAN MATEO', 'WILLACY', 'CAMP', 'DAVIS', 'BARNSTABLE', 'SARASOTA', 'PITTSYLVANIA', 'MACOUPIN', 'MIAMI-DADE', 'CLOUD', 'KITTSON', 'ISLAND', 'HOUSTON', 'PAYETTE', 'DOUGLAS', 'ALFALFA', 'TUOLUMNE', 'HIGHLAND', 'BARTOW', 'HAMPDEN', 'ATHENS', 'KINGMAN', 'DARKE', 'ESSEX', 'LACKAWANNA', 'PONTOTOC', 'ELBERT', 'FULTON', 'GONZALES', 'METCALFE', 'KNOTT', 'HARTFORD', 'LLANO', 'CLARKE', 'MONONA', 'DELTA', 'EVANGELINE', 'LATAH', 'SUWANNEE', 'SCIOTO', 'HARDY', 'SWIFT', 'WAPELLO', 'KING WILLIAM', 'HUMBOLDT', 'EDWARDS', 'KEARNEY', 'GRAHAM', 'LABETTE', 'SANPETE', 'SNYDER', 'ELLIS', 'JIM WELLS', 'LOS ANGELES', 'CODINGTON', 'OTTER TAIL', 'HARDEMAN', 'TIPPECANOE', 'GRAYSON', 'ACADIA', 'MERCER', 'MOHAVE', 'UNICOI', 'CLERMONT', 'MARICOPA', 'DYER', 'HERKIMER', 'ALLEGHANY', 'RENO', 'BLAIR', 'CORTLAND', 'VERNON', 'KEITH', 'DEL NORTE', 'BELMONT', 'FREESTONE', 'BON HOMME', 'NEWTON', 'OKEECHOBEE', 'GALLIA', 'KOOTENAI', 'VALLEY', 'BARTON', 'CREEK', 'GWINNETT', 'LONOKE', 'AROOSTOOK', 'LAMAR', 'GREENVILLE', 'EL PASO', 'ALPENA', 'ALLEGHENY', 'OCONTO', 'WESTMORELAND', 'DALLAS', 'CHESTERFIELD', 'HANSFORD', 'KITSAP', 'DUTCHESS', 'BLEDSOE', 'PETERSBURG BOROUGH', 'CASCADE', 'MARIPOSA', 'QUAY', 'PETTIS', 'SNOHOMISH', 'ROSS', 'DAKOTA', 'MEIGS', 'RENSSELAER', 'GRANT', 'BROWARD', 'APACHE', 'AVOYELLES', 'CONWAY', 'PENNINGTON', 'LYON', 'BLACKFORD', 'MONTEREY', 'HAAKON', 'CHARLTON', 'POWELL', 'BAILEY', 'DONIPHAN', 'POPE', 'CRANE', 'BLANCO', 'HONOLULU', 'ST. LUCIE', 'BEAVER', 'SAN BENITO', 'ERATH', 'MISSISSIPPI', 'POTTAWATTAMIE', 'SUTTER', 'CHARLEVOIX', 'IREDELL', 'CHEYENNE', 'NEW MADRID', 'OSCEOLA', 'KERSHAW', 'RANDOLPH', 'CLEAR CREEK', 'LAFAYETTE', 'NEWAYGO', 'ORANGEBURG', 'HOPKINS', 'WEST CARROLL', 'MAGOFFIN', 'OWEN', 'SALINE', 'HICKMAN', 'MECKLENBURG', 'NEW HAVEN', 'BARRY', 'CENTRE', 'BEAUFORT', 'MASON', 'LE FLORE', 'PRESQUE ISLE', 'HOLMES', 'SAN DIEGO', 'DADE', 'WASHBURN', 'GREGORY', 'BELTRAMI', 'HOWELL', 'BARNWELL', 'DIXIE', 'LEVY', 'RIO GRANDE', 'ST. CLAIR', 'LESLIE', 'BOONE', 'MADERA', 'OGLE', 'LA CROSSE', 'CLARK', 'WYANDOTTE', 'CALCASIEU', 'MONO', 'SUFFOLK', 'GRAFTON', 'WINONA', 'WORCESTER', 'YOUNG', 'BOYD', 'TRUMBULL', 'LAPORTE', 'NEZ PERCE', 'ALLEGAN', 'BEADLE', 'OGEMAW', 'ASHE', 'GEARY', 'CHOWAN', 'CLARENDON', 'GRADY', 'LEHIGH', 'GRAND TRAVERSE', 'FRIO', 'WOODWARD', 'KLEBERG', 'LEAVENWORTH', 'ATCHISON', 'WAGONER', 'GLOUCESTER', 'CHISAGO', 'BAMBERG', 'CERRO GORDO', 'SWEETWATER', 'BINGHAM', 'SHEBOYGAN', 'BOURBON', 'CLAY', 'VAL VERDE', 'HENDERSON', 'OCHILTREE', 'SANTA CLARA', 'HAMILTON', 'SIBLEY', 'ANDREW', 'FORD', 'CARTER', 'REDWOOD', 'BONNER', 'FAYETTE', 'STONE', 'GILMER', 'DICKINSON', 'MOUNTRAIL', 'ROCKCASTLE', 'CARLTON', 'PROVIDENCE', 'EDGAR', 'MATAGORDA', 'PEMBINA', 'MARTIN', 'CAPE MAY', 'WESTCHESTER', 'HOOD RIVER', 'BROOKS', 'PASCO', 'RIVERSIDE', 'CLATSOP', 'LINCOLN', 'LA PLATA', "QUEEN ANNE'S", 'KOOCHICHING', 'STARR', 'GENESEE', 'BREATHITT', 'LA PAZ', 'KENTON', 'STEVENS', 'TERRY', 'KIT CARSON', 'MOULTRIE', 'WILKIN', 'APPANOOSE', 'IRON', 'EL DORADO', 'BRANTLEY', 'DUCHESNE', 'CALLAHAN', 'SULLIVAN', 'BOSSIER', 'CANYON', 'DAWES', 'DESHA', 'BRANCH', 'GADSDEN', 'HERNANDO', 'WELLS', 'BRADFORD', 'CHASE', 'SIERRA', 'RUSK', 'PUSHMATAHA', 'CUSTER', 'BEAR LAKE', 'RHEA', 'SISKIYOU', 'ORANGE', 'HORRY', 'BOWMAN', 'GARFIELD', 'CHRISTIAN', 'MENOMINEE', 'KINGS', 'MOWER', 'SKAGIT', 'VILAS', 'HARRIS', 'MCNAIRY', 'CATTARAUGUS', 'FORT BEND', 'NAPA', 'MCLEOD', 'ATTALA', 'MODOC', 'FALL RIVER', 'JAY', 'LOGAN', 'CARBON', 'FRESNO', 'GOODHUE', 'ALACHUA', 'JEROME', 'CALHOUN', 'CHAVES', 'HURON', 'YAVAPAI', 'COLEMAN', 'SONOMA', 'KING', 'BAKER', 'COLUMBUS', 'FORSYTH', 'BEDFORD', 'NAVAJO', 'DEWEY', 'LEWIS', 'CHELAN', 'SCOTLAND', 'WASHTENAW', 'CLALLAM', 'NEW YORK', 'WEBSTER', 'LETCHER', 'VAN ZANDT', 'HENNEPIN', 'SOMERSET', 'WALSH', 'WELD', 'WARD', 'PLACER', 'GREENE', 'CACHE', 'CHARLESTON', 'STOKES', 'GALLATIN', 'PALO PINTO', 'CLEBURNE', 'STEPHENSON', 'LITTLE RIVER', 'JUNEAU', 'COLES', 'WADENA', 'SANGAMON', 'RUTHERFORD', 'NOBLE', 'BEE', 'BENTON', 'GILLESPIE', 'WEAKLEY', 'COLLETON', 'HOKE', 'POTTAWATOMIE', 'ROLETTE', 'GALVESTON', 'HOCKING', 'WILKINSON', 'MUSKEGON', 'FLOYD', 'CRAWFORD', 'HINDS', 'MONTROSE', 'VICTORIA', 'PRAIRIE', 'SUMTER', 'SALUDA', 'OKANOGAN', 'STEARNS', 'HARRISON', 'WHITMAN', 'CALDWELL', 'JOSEPHINE', 'CUMING', 'SENECA', 'KENDALL', 'HARNETT', 'PANOLA', 'COLORADO', 'NEWPORT', 'CROW WING', 'ANTRIM', 'SHIAWASSEE', 'HUDSON', 'PIERCE', 'HAMBLEN', 'ROCKINGHAM', 'PARKER', 'DAWSON', 'AMHERST', 'CHERRY', 'DESOTO', 'WOODFORD', 'ALAMOSA', 'BUCKS', 'PLATTE', 'PRESIDIO', 'GASTON', 'SANTA CRUZ', 'DAVIE', 'ALLEN', 'PRATT', "PRINCE GEORGE'S", 'SCOTT', 'GRAINGER', 'HOLT', 'STEWART', 'VAN BUREN', 'MURRAY', 'ROGERS', 'ANNE ARUNDEL', 'MUSKOGEE', 'SAN BERNARDINO', 'CROCKETT', 'NICHOLAS', 'MCCRACKEN', 'FOND DU LAC', 'ST. JAMES', 'NORTHUMBERLAND', 'TULSA', 'TEXAS', 'CHAUTAUQUA', 'GULF', 'BREWSTER', 'COLUSA', 'ALLENDALE', 'INDEPENDENCE', 'BENZIE', 'MCKINLEY', 'TRIGG', 'CHARLES MIX', 'REFUGIO', 'CHENANGO', 'INGHAM', 'RANSOM', 'CANADIAN', 'BARTHOLOMEW', 'BUFFALO', 'MCPHERSON', 'PIKE', 'MEEKER', 'HENDRY', 'WESTON', 'UNION', 'BURLINGTON', 'ISABELLA', 'DOUGHERTY', 'OCEANA', 'MACOMB', 'LEWIS AND CLARK', 'PITTSBURG', 'LINN', 'PORTER', 'DUNKLIN', 'PITT', 'HALL', 'OTTAWA', 'BOLLINGER', 'SUSQUEHANNA', 'YELLOWSTONE', 'HOWARD', 'YUBA', 'GASCONADE', 'ST. LANDRY', 'LUZERNE', 'YAMHILL', 'MCDOWELL', 'VERMILION', 'WINNEBAGO', 'WINNESHIEK', 'PENDLETON', 'MORRIS', 'MALHEUR', 'POWESHIEK', 'HENRY', 'WEST BATON ROUGE', 'HILL', 'KIDDER', 'BRULE', 'MCLENNAN', 'PHELPS', 'TRAVIS', 'COFFEE', 'JUAB', 'LOUISA', 'MENARD', 'LASSEN', 'RED RIVER', 'SHERMAN', 'WILL', 'KLICKITAT', 'SEARCY', 'LAMPASAS', 'ARCHER', 'EAGLE', 'VALENCIA', 'TREMPEALEAU', 'BENNETT', 'FARIBAULT', 'LOUDOUN', 'CABARRUS', 'WICHITA', 'PENDER', 'CROOK', 'CASEY', 'CUMBERLAND', 'BROOKE', 'HILLSDALE', 'EAST FELICIANA', 'HUGHES', 'MOODY', 'MORTON', 'RICHARDSON', 'HERTFORD', 'HASKELL', 'JONES', 'YELL', 'BALTIMORE', 'HARDEE', 'CARSON', 'ARMSTRONG', 'GILA', 'PERSON', 'CLACKAMAS', 'LATIMER', 'LUBBOCK', 'SAUK', 'PERSHING', 'MIDLAND', 'BROOMFIELD', 'CLEARWATER', 'SCHOOLCRAFT', 'SARATOGA', 'GARRARD', 'TOM GREEN', 'ST. MARY', 'WOODBURY', 'FAIRFIELD', 'LE SUEUR', 'COLLIER', 'KERR', 'CHITTENDEN', 'COTTON', 'BROOKINGS', 'MACON', 'WILSON', 'CIMARRON', 'SHERBURNE', 'SCHUYLKILL', 'MORROW', 'LARUE', 'MONTOUR', 'MOORE', 'FLAGLER', 'WHITE', 'COWLITZ', 'FAUQUIER', 'DE WITT', 'ONSLOW', 'OSAGE', 'BATH', 'MACKINAC', 'BAYLOR', 'HAMPTON', 'MARQUETTE', 'COMANCHE', 'ALLEGANY', 'ABBEVILLE', 'ATLANTIC', 'CRAVEN', 'PEND OREILLE', 'RAMSEY', 'SHAWNEE', 'BRYAN', 'CAMPBELL', 'MCKEAN', 'TRANSYLVANIA', 'BOND', 'RICE', 'SAN MIGUEL', 'CONVERSE', 'KITTITAS', 'MCINTOSH', 'GILCHRIST', 'COOPER', 'JACK', 'CHEBOYGAN', 'BELL', 'NIOBRARA', 'BELKNAP', 'BOULDER', 'ADAIR', 'LARIMER', 'CHESTER', 'NOTTOWAY', 'SHANNON', 'CHEROKEE', 'WAUPACA', 'PINELLAS', 'GAGE', 'PULASKI', 'HARLAN', 'SIOUX', 'BUTLER', 'AIKEN', 'ANSON', 'UMATILLA', 'WABASH', 'MULTNOMAH', 'BURLEIGH', 'ARKANSAS', 'MCMINN', 'BOUNDARY', 'AUGLAIZE', 'WOODRUFF', 'MADISON', 'ST. CROIX', 'BLUE EARTH', 'SEWARD', 'BILLINGS', 'DARLINGTON', 'SANDERS', 'PRINCE WILLIAM', 'DUNN', 'GARRETT', 'MILLER', 'GEM', 'EARLY', 'ST. JOHNS', 'LAKE', 'TALBOT', 'ADDISON', 'DICKSON', 'TAZEWELL', 'LUNA', 'CROSS', 'POINSETT', 'BREVARD', 'ST. LOUIS', 'FREDERICK', 'NUCKOLLS', 'SAN AUGUSTINE', 'GORDON', 'DOOR', 'HARDIN', 'DUBUQUE', 'NIAGARA', 'GRAY', 'NORMAN', 'HUTCHINSON', 'KOSSUTH', 'OLDHAM', 'ROCKBRIDGE', 'TOMPKINS', 'MCDONALD', 'COLFAX'}

In [21]:
FinalMergedData = pd.merge(CrimeUSCities, CostOfLiving, left_on='county_name', right_on='county', how='inner')
FinalMergedData.head()

,State,City,Population,V_crime,Murder,Rape,Robbery,Aggravated assault,Property crime,Burglary,...,family_member_count,housing_cost,food_cost,transportation_cost,healthcare_cost,other_necessities_cost,childcare_cost,taxes,total_cost,median_family_income
0,SOUTH CAROLINA,DUE WEST,"1,240",0,0.0,0,0,0,18,3,...,2p3c,11664.0,11860.31616,14687.4840,15738.01080,8523.78732,7933.82808,5336.97660,75744.4044,53251.199219
1,SOUTH CAROLINA,DUE WEST,"1,240",0,0.0,0,0,0,18,3,...,2p1c,8148.0,7670.25588,13942.0776,11276.38992,5731.57800,4327.54248,5573.68356,56669.5248,53251.199219
2,SOUTH CAROLINA,DUE WEST,"1,240",0,0.0,0,0,0,18,3,...,2p0c,6180.0,6162.82476,13218.5220,9045.58008,4472.29212,0.00000,5424.21096,44503.4292,53251.199219
3,SOUTH CAROLINA,DUE WEST,"1,240",0,0.0,0,0,0,18,3,...,1p4c,11664.0,11852.96484,13693.8276,13446.03120,8521.12356,7933.82808,3691.51572,70803.2928,53251.199219
4,SOUTH CAROLINA,DUE WEST,"1,240",0,0.0,0,0,0,18,3,...,1p3c,11664.0,9683.25948,13417.1964,11215.22016,7734.95364,7933.82808,4538.43756,66186.8964,53251.199219

In [22]:
FinalMergedData.shape

(279970, 45)

In [23]:
FinalMergedData.columns.unique()

Index(['State', 'City', 'Population', 'V_crime', 'Murder', 'Rape', 'Robbery',
       'Aggravated assault', 'Property crime', 'Burglary', 'Larceny-theft',
       'Motor vehicle theft', 'Arson2', 'city', 'city_ascii', 'state_id',
       'state_name', 'county_fips', 'county_name', 'lat', 'lng', 'population',
       'density', 'source', 'military', 'incorporated', 'timezone', 'ranking',
       'zips', 'id', 'case_id', 'state', 'isMetro', 'areaname', 'county',
       'family_member_count', 'housing_cost', 'food_cost',
       'transportation_cost', 'healthcare_cost', 'other_necessities_cost',
       'childcare_cost', 'taxes', 'total_cost', 'median_family_income'],
      dtype='object')

In [24]:
columns_to_drop = ['state_id', 'lat', 'lng', 'timezone', 'zips', 'id', 'case_id', 'state', 'county']
FinalMergedData.drop(columns=columns_to_drop, inplace=True)
FinalMergedData.head()

,State,City,Population,V_crime,Murder,Rape,Robbery,Aggravated assault,Property crime,Burglary,...,family_member_count,housing_cost,food_cost,transportation_cost,healthcare_cost,other_necessities_cost,childcare_cost,taxes,total_cost,median_family_income
0,SOUTH CAROLINA,DUE WEST,"1,240",0,0.0,0,0,0,18,3,...,2p3c,11664.0,11860.31616,14687.4840,15738.01080,8523.78732,7933.82808,5336.97660,75744.4044,53251.199219
1,SOUTH CAROLINA,DUE WEST,"1,240",0,0.0,0,0,0,18,3,...,2p1c,8148.0,7670.25588,13942.0776,11276.38992,5731.57800,4327.54248,5573.68356,56669.5248,53251.199219
2,SOUTH CAROLINA,DUE WEST,"1,240",0,0.0,0,0,0,18,3,...,2p0c,6180.0,6162.82476,13218.5220,9045.58008,4472.29212,0.00000,5424.21096,44503.4292,53251.199219
3,SOUTH CAROLINA,DUE WEST,"1,240",0,0.0,0,0,0,18,3,...,1p4c,11664.0,11852.96484,13693.8276,13446.03120,8521.12356,7933.82808,3691.51572,70803.2928,53251.199219
4,SOUTH CAROLINA,DUE WEST,"1,240",0,0.0,0,0,0,18,3,...,1p3c,11664.0,9683.25948,13417.1964,11215.22016,7734.95364,7933.82808,4538.43756,66186.8964,53251.199219

In [25]:
FinalMergedData.columns.unique()

Index(['State', 'City', 'Population', 'V_crime', 'Murder', 'Rape', 'Robbery',
       'Aggravated assault', 'Property crime', 'Burglary', 'Larceny-theft',
       'Motor vehicle theft', 'Arson2', 'city', 'city_ascii', 'state_name',
       'county_fips', 'county_name', 'population', 'density', 'source',
       'military', 'incorporated', 'ranking', 'isMetro', 'areaname',
       'family_member_count', 'housing_cost', 'food_cost',
       'transportation_cost', 'healthcare_cost', 'other_necessities_cost',
       'childcare_cost', 'taxes', 'total_cost', 'median_family_income'],
      dtype='object')

In [26]:
# prompt: count zero values in each column for each column

zero_counts = FinalMergedData.eq(0).sum(axis=0)
for column, count in zero_counts.items():
  print(f"Column: {column}, Zero values: {count}")

Column: State, Zero values: 0
Column: City, Zero values: 0
Column: Population, Zero values: 0
Column: V_crime, Zero values: 0
Column: Murder, Zero values: 218910
Column: Rape, Zero values: 0
Column: Robbery, Zero values: 0
Column: Aggravated assault, Zero values: 0
Column: Property crime, Zero values: 0
Column: Burglary, Zero values: 0
Column: Larceny-theft, Zero values: 0
Column: Motor vehicle theft, Zero values: 0
Column: Arson2, Zero values: 0
Column: city, Zero values: 0
Column: city_ascii, Zero values: 0
Column: state_name, Zero values: 0
Column: county_fips, Zero values: 0
Column: county_name, Zero values: 0
Column: population, Zero values: 0
Column: density, Zero values: 0
Column: source, Zero values: 0
Column: military, Zero values: 279970
Column: incorporated, Zero values: 930
Column: ranking, Zero values: 0
Column: isMetro, Zero values: 160180
Column: areaname, Zero values: 0
Column: family_member_count, Zero values: 0
Column: housing_cost, Zero values: 0
Column: food_cost, Zero values: 0
Column: transportation_cost, Zero values: 0
Column: healthcare_cost, Zero values: 0
Column: other_necessities_cost, Zero values: 0
Column: childcare_cost, Zero values: 55994
Column: taxes, Zero values: 0
Column: total_cost, Zero values: 0
Column: median_family_income, Zero values: 0

In [27]:
columns_to_drop = ['Arson2', 'military','childcare_cost']
FinalMergedData.drop(columns=columns_to_drop, inplace=True)
FinalMergedData.head()

,State,City,Population,V_crime,Murder,Rape,Robbery,Aggravated assault,Property crime,Burglary,...,areaname,family_member_count,housing_cost,food_cost,transportation_cost,healthcare_cost,other_necessities_cost,taxes,total_cost,median_family_income
0,SOUTH CAROLINA,DUE WEST,"1,240",0,0.0,0,0,0,18,3,...,"Abbeville County, SC",2p3c,11664.0,11860.31616,14687.4840,15738.01080,8523.78732,5336.97660,75744.4044,53251.199219
1,SOUTH CAROLINA,DUE WEST,"1,240",0,0.0,0,0,0,18,3,...,"Abbeville County, SC",2p1c,8148.0,7670.25588,13942.0776,11276.38992,5731.57800,5573.68356,56669.5248,53251.199219
2,SOUTH CAROLINA,DUE WEST,"1,240",0,0.0,0,0,0,18,3,...,"Abbeville County, SC",2p0c,6180.0,6162.82476,13218.5220,9045.58008,4472.29212,5424.21096,44503.4292,53251.199219
3,SOUTH CAROLINA,DUE WEST,"1,240",0,0.0,0,0,0,18,3,...,"Abbeville County, SC",1p4c,11664.0,11852.96484,13693.8276,13446.03120,8521.12356,3691.51572,70803.2928,53251.199219
4,SOUTH CAROLINA,DUE WEST,"1,240",0,0.0,0,0,0,18,3,...,"Abbeville County, SC",1p3c,11664.0,9683.25948,13417.1964,11215.22016,7734.95364,4538.43756,66186.8964,53251.199219

In [31]:
FinalMergedData.columns.unique()

Index(['State', 'City', 'Population', 'V_crime', 'Murder', 'Rape', 'Robbery',
       'Aggravated assault', 'Property crime', 'Burglary', 'Larceny-theft',
       'Motor vehicle theft', 'city', 'city_ascii', 'state_name',
       'county_fips', 'county_name', 'population', 'density', 'source',
       'incorporated', 'ranking', 'isMetro', 'areaname', 'family_member_count',
       'housing_cost', 'food_cost', 'transportation_cost', 'healthcare_cost',
       'other_necessities_cost', 'taxes', 'total_cost',
       'median_family_income'],
      dtype='object')

In [32]:
# prompt: download this dataset

from google.colab import files
FinalMergedData.to_csv('FinalMergedData.csv')
files.download('FinalMergedData.csv')

In [33]:
filtered_df = FinalMergedData[FinalMergedData['family_member_count'] == '2p2c']
filtered_df.shape

(27997, 33)

In [34]:
filtered_df.to_csv('FinalMergedData2.csv')
files.download('FinalMergedData2.csv')

In [36]:
filtered_df['food_cost'].unique().size

196

In [38]:
ff_filtered_df = filtered_df.drop_duplicates(subset=['City', 'State'])
ff_filtered_df.shape

(6242, 33)

In [39]:
ff_filtered_df.to_csv('FinalMergedData3.csv')
files.download('FinalMergedData3.csv')

In [40]:
ff_filtered_df

,State,City,Population,V_crime,Murder,Rape,Robbery,Aggravated assault,Property crime,Burglary,...,areaname,family_member_count,housing_cost,food_cost,transportation_cost,healthcare_cost,other_necessities_cost,taxes,total_cost,median_family_income
7,SOUTH CAROLINA,DUE WEST,"1,240",0,0.0,0,0,0,18,3,...,"Abbeville County, SC",2p2c,8148.0,9714.21384,14433.5988,13507.2000,6472.18428,4582.35168,63942.8376,53251.199219
17,SOUTH CAROLINA,CALHOUN FALLS,"1,912",14,2.0,0,0,12,31,11,...,"Abbeville County, SC",2p2c,8148.0,9714.21384,14433.5988,13507.2000,6472.18428,4582.35168,63942.8376,53251.199219
27,SOUTH CAROLINA,ABBEVILLE,"5,017",47,9.0,4,4,30,123,29,...,"Abbeville County, SC",2p2c,8148.0,9714.21384,14433.5988,13507.2000,6472.18428,4582.35168,63942.8376,53251.199219
35,LOUISIANA,CHURCH POINT,"4,424",39,1.0,1,0,37,78,18,...,"Acadia Parish, LA HUD Metro FMR Area",2p2c,8700.0,9114.57060,13866.2988,18289.0836,6454.92192,7041.48408,72526.2192,58169.695312
45,LOUISIANA,CROWLEY,"12,621",158,1.0,8,14,135,528,132,...,"Acadia Parish, LA HUD Metro FMR Area",2p2c,8700.0,9114.57060,13866.2988,18289.0836,6454.92192,7041.48408,72526.2192,58169.695312
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
279880,COLORADO,WRAY,"2,331",1,0.0,1,0,0,1,0,...,"Yuma, AZ MSA",2p2c,11124.0,8155.14252,14254.0104,20214.3576,6985.59372,8670.21900,85373.5896,51688.371094
279900,COLORADO,YUMA,"3,452",4,0.0,1,0,3,19,3,...,"Yuma, AZ MSA",2p2c,11124.0,8155.14252,14254.0104,20214.3576,6985.59372,8670.21900,85373.5896,51688.371094
279920,ARIZONA,WELLTON,"3,048",5,0.0,1,0,4,31,9,...,"Yuma, AZ MSA",2p2c,11124.0,8155.14252,14254.0104,20214.3576,6985.59372,8670.21900,85373.5896,51688.371094
279940,ARIZONA,YUMA,"98,769",376,11.0,27,29,309,"2,302",483,...,"Yuma, AZ MSA",2p2c,11124.0,8155.14252,14254.0104,20214.3576,6985.59372,8670.21900,85373.5896,51688.371094
279963,TEXAS,CRYSTAL CITY,"7,283",9,0.0,0,0,9,41,22,...,"Zavala County, TX",2p2c,8808.0,7285.66044,13672.4196,16453.0416,5831.36832,3719.66016,63917.2788,37248.113281